# Generated by Django 6.0.4 on 2026-05-03 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveIntegerField(default=5)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='crud_app.habitacion')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='crud_app.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
