# Generated by Django 6.0.4 on 2026-05-01 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('estandar', '🛏️ Estándar'), ('deluxe', '🛏️ Deluxe'), ('suite', '⭐ Suite'), ('suite_ejecutiva', '👔 Suite Ejecutiva'), ('suite_presidencial', '👑 Suite Presidencial'), ('villa', '🏡 Villa Familiar')], default='estandar', max_length=30)),
                ('descripcion', models.TextField()),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.PositiveIntegerField(default=2)),
                ('piso', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('disponible', '🟢 Disponible'), ('ocupada', '🔵 Ocupada'), ('limpieza', '🟡 Limpieza'), ('mantenimiento', '🔴 Mantenimiento')], default='disponible', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='habitaciones/')),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('amenidades', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reserva', '🛏️ Reserva'), ('pago', '💳 Pago'), ('promo', '⭐ Promoción'), ('alerta', '⚠️ Alerta'), ('info', '📢 Info')], default='info', max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('confirmada', '✅ Confirmada'), ('cancelada', '❌ Cancelada'), ('completada', '🏁 Completada'), ('en_curso', '🔵 En curso')], default='pendiente', max_length=20)),
                ('check_in', models.DateField(default='2024-01-01')),
                ('check_out', models.DateField(default='2024-01-02')),
                ('huespedes', models.PositiveIntegerField(default=1)),
                ('adultos', models.PositiveIntegerField(default=1)),
                ('ninos', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_huesped', models.CharField(default='', max_length=100)),
                ('documento', models.CharField(default='', max_length=20)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('solicitudes', models.TextField(blank=True, null=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='crud_app.habitacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('tarjeta', '💳 Tarjeta'), ('transferencia', '🏦 Transferencia'), ('efectivo', '💵 Efectivo'), ('pse', '📱 PSE')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('confirmado', '✅ Confirmado'), ('rechazado', '❌ Rechazado'), ('reembolsado', '↩️ Reembolsado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(max_length=20, unique=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('nombre_titular', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=4, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='crud_app.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('limpieza', '🧹 Limpieza'), ('room_service', '🍽️ Room Service'), ('lavanderia', '👕 Lavandería'), ('spa', '💆 Spa'), ('transporte', '🚗 Transporte'), ('otro', '📦 Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('en_proceso', '🔵 En proceso'), ('completado', '✅ Completado'), ('cancelado', '❌ Cancelado')], default='pendiente', max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='crud_app.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='crud_app.habitacion')),
            ],
            options={
                'unique_together': {('usuario', 'habitacion')},
            },
        ),
    ]
