# Generated by Django 6.0.4 on 2026-05-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagenes_galeria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
