# Generated by Django 6.0.4 on 2026-05-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_habitacion_imagenes_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='habitaciones/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='crud_app.habitacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
