# Generated by Django 6.0.4 on 2026-05-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_fotohabitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('disponible', '🟢 Disponible'), ('reservada', '📋 Reservada'), ('ocupada', '🔵 Ocupada'), ('limpieza', '🟡 Limpieza'), ('mantenimiento', '🔴 Mantenimiento')], default='disponible', max_length=20),
        ),
    ]
